{
 "title": "Service",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime in minutes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor((time() - process_start_time_seconds) / 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime in days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor((time() - process_start_time_seconds) / 60 / 60 / 24)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Endpoint Avg Bucket Sumary in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{job=\"api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Endpoint Avg Request Sumary in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Time per User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "process_cpu_user_seconds_total{job=\"api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}